name: 'Setup Racket environment'
description: 'Setup a Racket environment and add it to the PATH.'
author: 'Bogdanp'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  architecture:
    description: 'The target architecture (arm32, arm64, x86, x64) of the Racket VM.'
    default: 'x64'
  distribution:
    description: 'The target distribution (minimal, full) of Racket.'
    default: 'full'
  variant:
    description: 'The target variant (BC, CS) of Racket. Defaults to CS if the version is >= 8.0, otherwise BC.'
    default: ''
  version:
    description: 'Racket version to use.'
    required: true
  catalogs:
    description: 'A comma-separated list of package catalogs to use when installing packages.'
    default: ''
  local_catalogs:
    description: 'A comma-separated list of paths to create local catalogs in.'
    default: ''
  packages:
    description: 'A comma-separated list of packages to install from the Package Catalog.'
    default: ''
  dest:
    description: 'Installation destination. Linux only.'
    default: ''
  sudo:
    description: 'Use sudo or not (always, never).'
    default: ''
runs:
  using: 'node16'
  main: 'lib/setup-racket.js'
