name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * MON"

jobs:
  run:
    name: "Build using Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }}) on '${{ matrix.os }}'"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        racket-version: ["7.5", "7.6", "7.7", "current"]
        racket-variant: ["regular", "CS"]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: npm test
      run: npm test

    - name: npm build
      run: npm build

    - name: run
      run: node lib/setup-racket.js
      env:
        INPUT_VARIANT: ${{ matrix.racket-variant }}
        INPUT_VERSION: ${{ matrix.racket-version }}

    - name: test racket
      run: racket -e '(displayln 42)'

    - name: test package installation
      run: raco pkg install nevermore

  run_docker:
    name: "Build in Docker"
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
    - uses: actions/checkout@v1
    - uses: Bogdanp/setup-racket@master
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.7'
    - name: test racket
      run: racket -e '(displayln 42)'

  run_docker_catalogs_packages:
    name: "Build in Docker with custom catalogs and install packages"
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
    - uses: actions/checkout@v1
    - uses: Bogdanp/setup-racket@master
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.7'
        catalogs: 'http://racksnaps.defn.io/built-snapshots/2020/05/02/catalog/'
        packages: nevermore, component
    - name: test racket
      run: racket -e '(require nevermore) (american-gods)'

  run_multi:
    name: "Install multiple versions"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: npm build
      run: npm build

    - name: install BC
      run: node lib/setup-racket.js
      env:
        INPUT_VARIANT: 'regular'
        INPUT_VERSION: '7.7'
        INPUT_DEST: /opt/racketbc

    - name: install CS
      run: node lib/setup-racket.js
      env:
        INPUT_VARIANT: 'regular'
        INPUT_VERSION: '7.7'
        INPUT_DEST: /opt/racketcs

    - name: test BC
      run: /opt/racketbc/bin/racket -e '(displayln 42)'

    - name: test CS
      run: /opt/racketcs/bin/racket -e '(displayln 42)'
