name: CI
on: [push]
jobs:
  run:
    name: "Build using Racket '${{ matrix.racket-version }}'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["7.3", "7.4", "current"]
        racket-variant: ["regular", "CS"]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: npm test
      run: npm test

    - name: npm build
      run: npm build

    - name: run
      run: node lib/setup-racket.js
      env:
        INPUT_VARIANT: ${{ matrix.racket-variant }}
        INPUT_VERSION: ${{ matrix.racket-version }}

    - name: test Racket
      run: racket -e '(displayln "hi!")'
